raspimouse:
  ros__parameters:
    odometry_scale_left_wheel : 1.0
    odometry_scale_right_wheel: 1.0
    use_light_sensors         : true
    use_pulse_counters        : false
    wheel_diameter            : 0.048
    wheel_tread               : 0.0925
    pulses_per_revolution     : 400.0
    light_sensors_hz          : 100.0
    initial_motor_power       : false
